import re
from bs4 import BeautifulSoup

# We need to robustly parse pubs_fitz.txt
with open("pubs_fitz.txt", "r", encoding="utf-8") as f:
    text = f.read()

# Clean all headers/footers first!
text = re.sub(r'Dasgupta Research Group @ K-…\nHome\nResearch\nAbout Saswata\nGro\n3/23/26, 1:26 AM\nDasgupta Research Group @ K-State - Publications\nhttps://www\.drgatksu\.com/publications\n\d+/37\n', '', text)
text = re.sub(r'Dasgupta Research Group @ K-…\n3/23/26, 1:26 AM\nDasgupta Research Group @ K-State - Publications\nhttps://www\.drgatksu\.com/publications\n\d+/37\n', '', text)
# Any remaining
text = re.sub(r'Dasgupta Research Group @ K-…\n.*?\d+/37\n', '', text, flags=re.MULTILINE|re.DOTALL)
# It's better to just go line by line and ignore those lines.

lines = text.split('\n')
clean_lines = []
skip = False
for l in lines:
    l = l.strip()
    if not l: continue
    if l in ["Publications", "Home", "Research", "About Saswata", "Gro", "3/23/26, 1:26 AM", "Dasgupta Research Group @ K-State - Publications"]:
        continue
    if l.startswith("https://"): continue
    if re.match(r'^\d+/37$', l): continue
    if "Dasgupta Research Group" in l: continue
    if "📍" in l or "Chemistry and Biochemistry" in l or "66506" in l: continue
    
    # Also ignore weird 1 character lines like 'i', 'f', 'd', 'l', 'b', 'h' generated by page breaks
    if len(l) == 1 and l in "ifdlbh": continue
    if l in ["14) Eli", "12) B l", "10) H", "9) D", "8) A", "7) El", "6) G", "5) S f", "1) S", "id f"]: continue
    
    clean_lines.append(l)

# Re-join and split by \d+)
clean_text = "\n".join(clean_lines)
parts = re.split(r'\n(\d+)\)\s*', '\n' + clean_text)

pubs = {}
for i in range(1, len(parts), 2):
    num = parts[i]
    block = parts[i+1].strip()
    
    # In the block, the abstract starts right after the line containing ") link" or isolated "link"
    block_lines = block.split('\n')
    
    aj_idx = -1
    for idx, bl in enumerate(block_lines):
        if "link" in bl and ("20" in bl or "Dasgupta" in bl or "Chem" in bl):
            aj_idx = idx
            break
        elif bl == "link":
            aj_idx = idx - 1  # the previous line was the author line
            break
            
    if aj_idx == -1:
        # Fallback if "link" is completely missing
        for idx, bl in enumerate(block_lines):
            if "Dasgupta" in bl and ("Chem" in bl or "Phys" in bl or "Soc" in bl):
                aj_idx = idx
                break
                
    if aj_idx == -1: print(f"Could not find author line for {num}"); continue
    
    # Title is everything before aj_idx
    title_lines = block_lines[:aj_idx]
    title = " ".join(title_lines).strip()
    
    # Author/Journal
    if block_lines[aj_idx+1] == "link":
        aj_line = block_lines[aj_idx]
        aj_end_idx = aj_idx + 1
    else:
        # aj_line spans maybe? Sometimes it's broken over two lines in PDF!
        # Let's see if the line starts with a parenthesis or year.
        aj_str = block_lines[aj_idx]
        # if the line BEFORE aj_idx contains Dasgupta but we picked aj_idx because it has 'link'
        if "Dasgupta" not in aj_str and aj_idx > 0 and "Dasgupta" in block_lines[aj_idx-1]:
            # The author line is broken into two
            aj_str = block_lines[aj_idx-1] + " " + aj_str
            title = " ".join(block_lines[:aj_idx-1]).strip()
            
        aj_line = aj_str
        aj_end_idx = aj_idx
        
    # Clean aj_line
    aj_line = aj_line.replace(")) link", ")").replace(") link", ")").replace(" link", "").strip()
    if not aj_line.endswith(")") and aj_line.count("(") > 0:
        # maybe missing parenthesis?
        aj_line += ")"
        
    abstract_lines = block_lines[aj_end_idx+1:]
    # if the first abstract line is "link", skip it
    if abstract_lines and abstract_lines[0] == "link":
        abstract_lines = abstract_lines[1:]
        
    abstract = " ".join(abstract_lines).strip()
    pubs[num] = {"title": title, "aj": aj_line, "abs": abstract}

with open("publications.html", "r", encoding="utf-8") as f:
    soup = BeautifulSoup(f.read(), "html.parser")

for pub in soup.find_all(class_='pub-item'):
    h3 = pub.find('h3')
    if not h3: continue
    m = re.search(r'^(\d+)\.', h3.get_text())
    if not m: continue
    num = m.group(1)
    
    if num in pubs:
        pd = pubs[num]
        h3.string = f"{num}. {pd['title']}"
        details = pub.find(class_='pub-details')
        if details:
            ps = details.find_all('p', recursive=False)
            if ps:
                # keep class="pub-authors"
                ps[0].string = pd['aj']
            abs_div = details.find(class_='pub-abstract')
            if abs_div:
                abs_div.string = pd['abs']

with open("publications.html", "w", encoding="utf-8") as f:
    f.write(str(soup))
print("fixed")
